query_template: >
  SELECT 
    SUBSTRING(SiteName, 1, 6) kfme, 
    CASE SUBSTRING(SiteName, 12, 2) 
      WHEN 'p1' THEN sq.Path1Geometry 
      WHEN 'p2' THEN sq.Path2Geometry 
      ELSE NULL END LineGeometry,
    oi.LatObs, 
    oi.LonObs, 
    oi.LatItem, 
    oi.LonItem, 
    ObsDate, 
    NameCS, 
    NameLA 
  FROM `vw_lsd_oi` oi 
    INNER JOIN `vw_lsd_ol` ol 
      ON oi.ObsListId = ol.Id 
    LEFT JOIN codebook.TaxonRarity tr 
      ON oi.SpeciesId = tr.Taxon_ID 
    INNER JOIN project.LSD_Square sq 
      ON SUBSTRING(ol.SiteName, 1, 6) = sq.Square COLLATE utf8mb4_czech_ci 
  {conditions};
