query_template: "SELECT * FROM project.LSD_Square WHERE {conditions}"
parameters:
  - name: "username"
    type: "str"
    help: "User's username to filter by"
  - name: "age"
    type: "int"
    help: "Minimum age for filtering users"
